// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatPark.Models;

namespace NatPark.Migrations
{
    [DbContext(typeof(NatParkContext))]
    [Migration("20220819200631_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NatPark.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Popularity")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Location = "Kalamath Falls, OR",
                            Name = "Crater Lake National Park",
                            Popularity = 5
                        },
                        new
                        {
                            ParkId = 2,
                            Location = "Glacier County, MT",
                            Name = "Glacier National Park",
                            Popularity = 7
                        },
                        new
                        {
                            ParkId = 3,
                            Location = "St. Louis, MO",
                            Name = "Gateway Arch National Park",
                            Popularity = 4
                        },
                        new
                        {
                            ParkId = 4,
                            Location = "Rapid City, SD",
                            Name = "Badlands National Park",
                            Popularity = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
